import Head from 'next/head'
import Nav from '../components/Nav'
import  Results  from '../components/Results'
import Header from '../components/Header'
import requests from '../utils/requests'


export default function Home({results}) {
  // console.log(results)
  return (
    <div>
      <Head>
        {/* 페이지마다 변경되어야 할 부분 */}
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      {/* Header component */}
      <Header/>
      {/* Nav component */}
      <Nav/>
      {/* Results component */}
      <Results results={results}/>
    </div>
  )
}
//server에서 먼저 렌더링을 하고 그 결과값을 client로 전달한다.
export async function getServerSideProps(context){
  const genre = context.query.genre;

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
  .then(res => res.json())

  return {
    props: {
      results:request.results
    }
  }
}